services:
  db:
    image: mysql:9.3.0
    container_name: gestao-de-eventos-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gestao-network

  backend:
    build:
      context: ./backend/gestaoeventos
    environment:
      - SPRING_PROFILES_ACTIVE=${BACKEND_ENV}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - db
    networks:
      - gestao-network

  frontend:
    build:
      context: ./frontend/gestao-eventos
      dockerfile: Dockerfile
    container_name: gestao-de-eventos-frontend
    environment:
      - API_URL=${API_URL}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - gestao-network

networks:
  gestao-network:
    driver: bridge

volumes:
  db_data: